const {Engine,Runner,Bodies,Body,Composite,Events}=Matter;
const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d');
const engine=Engine.create({gravity:{x:0,y:1,scale:.001}});let runner=null,mode='build',tool='domino',items=[],initial=[],score=0,combo=1,lastHit=0,activated=new Set();
const $=s=>document.querySelector(s), msg=$('#message');
function size(){const r=canvas.getBoundingClientRect(),d=devicePixelRatio||1;canvas.width=r.width*d;canvas.height=r.height*d;ctx.setTransform(d,0,0,d,0,0);walls()}addEventListener('resize',size);
let boundaries=[];
function walls(){boundaries.forEach(b=>Composite.remove(engine.world,b));let w=canvas.clientWidth,h=canvas.clientHeight;boundaries=[Bodies.rectangle(w/2,h+20,w,40,{isStatic:true}),Bodies.rectangle(-20,h/2,40,h,{isStatic:true}),Bodies.rectangle(w+20,h/2,40,h,{isStatic:true})];Composite.add(engine.world,boundaries)}
function add(type,x,y){if(mode!=='build')return;let b,o={friction:.6,restitution:.15,label:type};if(type==='domino')b=Bodies.rectangle(x,y,12,54,o);if(type==='ball')b=Bodies.circle(x,y,16,{...o,restitution:.45});if(type==='ramp')b=Bodies.rectangle(x,y,100,10,{...o,isStatic:true,angle:-.35});if(type==='spring')b=Bodies.rectangle(x,y,42,12,{...o,isStatic:true,restitution:1.5});if(type==='target')b=Bodies.circle(x,y,23,{...o,isStatic:true,isSensor:true});if(!b)return;items.push(b);Composite.add(engine.world,b);snapshot();tone(180,.025,.025)}
function snapshot(){initial=items.map(b=>({type:b.label,x:b.position.x,y:b.position.y,a:b.angle}))}
function rebuild(){items.forEach(b=>Composite.remove(engine.world,b));items=[];initial.forEach(q=>{add(q.type,q.x,q.y);Body.setAngle(items.at(-1),q.a)});mode='build';score=0;combo=1;activated.clear();update();msg.textContent='BUILD YOUR MACHINE'}
function go(){if(mode==='run'||!items.length)return;mode='run';msg.textContent='CHAIN REACTION!';items.forEach(b=>{if(b.label!=='ramp'&&b.label!=='spring'&&b.label!=='target')Body.setStatic(b,false)});runner=Runner.create();Runner.run(runner,engine);tone(280,.12,.08)}
function points(n){let now=performance.now();combo=now-lastHit<900?Math.min(9.9,combo+.15):1;lastHit=now;score+=Math.round(n*combo);update()}
function update(){scoreEl.textContent=score;comboEl.textContent='×'+combo.toFixed(1);let best=+localStorage.crBest||0;if(score>best)localStorage.crBest=score;bestEl.textContent=Math.max(best,score)}
const scoreEl=$('#score'),comboEl=$('#combo'),bestEl=$('#best');update();
Events.on(engine,'collisionStart',e=>{if(mode!=='run')return;e.pairs.forEach(p=>{let a=p.bodyA,b=p.bodyB;let moving=[a,b].find(x=>!x.isStatic);if(moving&&!boundaries.includes(a)&&!boundaries.includes(b)){points(10);tone(110+Math.random()*80,.025,.018)}let spring=[a,b].find(x=>x.label==='spring');if(spring&&moving&&moving!==spring){Body.applyForce(moving,moving.position,{x:0,y:-.035});points(40);tone(520,.08,.05)}let target=[a,b].find(x=>x.label==='target');if(target&&!activated.has(target.id)){activated.add(target.id);points(250);msg.textContent='TARGET HIT!';tone(760,.18,.08)}})});
let ac=null;function tone(f,d,v){try{ac??=new (AudioContext||webkitAudioContext)();let o=ac.createOscillator(),g=ac.createGain();o.frequency.value=f;o.type='sine';g.gain.setValueAtTime(v,ac.currentTime);g.gain.exponentialRampToValueAtTime(.001,ac.currentTime+d);o.connect(g).connect(ac.destination);o.start();o.stop(ac.currentTime+d)}catch{}}
canvas.addEventListener('pointerdown',e=>{let r=canvas.getBoundingClientRect();add(tool,e.clientX-r.left,e.clientY-r.top)});
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{tool=b.dataset.tool;document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('active',x===b))});document.querySelector('[data-tool=domino]').classList.add('active');
$('#go').onclick=go;$('#reset').onclick=()=>{if(runner)Runner.stop(runner);rebuild()};$('#clear').onclick=()=>{if(mode==='build'){items.forEach(b=>Composite.remove(engine.world,b));items=[];snapshot()}};$('#undo').onclick=()=>{if(mode==='build'&&items.length){Composite.remove(engine.world,items.pop());snapshot()}};
function draw(){let w=canvas.clientWidth,h=canvas.clientHeight;ctx.clearRect(0,0,w,h);ctx.strokeStyle='#293244';ctx.lineWidth=1;for(let x=20;x<w;x+=40){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke()}for(let y=20;y<h;y+=40){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke()}items.forEach(b=>{ctx.save();ctx.translate(b.position.x,b.position.y);ctx.rotate(b.angle);ctx.lineWidth=2;if(b.label==='domino'){ctx.fillStyle='#e7edf5';ctx.fillRect(-6,-27,12,54);ctx.strokeStyle='#98a8bb';ctx.strokeRect(-6,-27,12,54)}if(b.label==='ball'){ctx.fillStyle='#69dcff';ctx.beginPath();ctx.arc(0,0,16,0,7);ctx.fill()}if(b.label==='ramp'){ctx.fillStyle='#8a97aa';ctx.fillRect(-50,-5,100,10)}if(b.label==='spring'){ctx.strokeStyle='#ffd166';ctx.lineWidth=4;ctx.beginPath();for(let i=-18;i<=18;i+=6)ctx.lineTo(i,(i/6%2)*8-4);ctx.stroke()}if(b.label==='target'){ctx.strokeStyle=activated.has(b.id)?'#62f58a':'#ff6680';ctx.lineWidth=5;ctx.beginPath();ctx.arc(0,0,23,0,7);ctx.stroke();ctx.beginPath();ctx.arc(0,0,9,0,7);ctx.stroke()}ctx.restore()});requestAnimationFrame(draw)}size();draw();