const {Engine,Runner,Bodies,Body,Composite,Events}=Matter;
const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d');
const engine=Engine.create({gravity:{x:0,y:1,scale:.001}});let runner=null,mode='build',tool='domino',items=[],initial=[],score=0,combo=1,lastHit=0,activated=new Set();
const $=s=>document.querySelector(s), msg=$('#message');
function size(){const r=canvas.getBoundingClientRect(),d=devicePixelRatio||1;canvas.width=r.width*d;canvas.height=r.height*d;ctx.setTransform(d,0,0,d,0,0);walls()}addEventListener('resize',size);
let boundaries=[];
function walls(){boundaries.forEach(b=>Composite.remove(engine.world,b));let w=canvas.clientWidth,h=canvas.clientHeight;boundaries=[Bodies.rectangle(w/2,h+20,w,40,{isStatic:true}),Bodies.rectangle(-20,h/2,40,h,{isStatic:true}),Bodies.rectangle(w+20,h/2,40,h,{isStatic:true})];Composite.add(engine.world,boundaries)}
function add(type,x,y){if(mode!=='build')return;let b=createBody(type,x,y);if(!b)return;items.push(b);Composite.add(engine.world,b);snapshot();tone(180,.025,.025)}
function snapshot(){initial=items.map(b=>({type:b.label,x:b.position.x,y:b.position.y,a:b.angle}))}
function rebuild(){const saved=initial.map(q=>({...q}));items.forEach(b=>Composite.remove(engine.world,b));items=[];mode='build';initial=saved;for(const q of saved){let b=createBody(q.type,q.x,q.y);if(b){Body.setAngle(b,q.a);items.push(b);Composite.add(engine.world,b)}}score=0;combo=1;activated.clear();lastHit=0;update();msg.textContent='BUILD YOUR MACHINE'}
function createBody(type,x,y){let b,o={friction:.6,restitution:.15,label:type};if(type==='domino')b=Bodies.rectangle(x,y,12,54,o);if(type==='ball')b=Bodies.circle(x,y,16,{...o,restitution:.45});if(type==='ramp')b=Bodies.rectangle(x,y,100,10,{...o,isStatic:true,angle:-.35});if(type==='spring')b=Bodies.rectangle(x,y,42,12,{...o,isStatic:true,restitution:1.5});if(type==='target')b=Bodies.circle(x,y,23,{...o,isStatic:true,isSensor:true});return b}
function go(){if(mode==='run'||!items.length)return;mode='run';msg.textContent='CHAIN REACTION!';items.forEach(b=>{if(b.label!=='ramp'&&b.label!=='spring'&&b.label!=='target')Body.setStatic(b,false)});runner=Runner.create();Runner.run(runner,engine);tone(280,.12,.08)}
function points(n){let now=performance.now();combo=now-lastHit<900?Math.min(9.9,combo+.15):1;lastHit=now;score+=Math.round(n*combo);update()}
function update(){scoreEl.textContent=score;comboEl.textContent='×'+combo.toFixed(1);let best=+localStorage.crBest||0;if(score>best)localStorage.crBest=score;bestEl.textContent=Math.max(best,score)}
const scoreEl=$('#score'),comboEl=$('#combo'),bestEl=$('#best');update();
Events.on(engine,'collisionStart',e=>{if(mode!=='run')return;e.pairs.forEach(p=>{let a=p.bodyA,b=p.bodyB;let moving=[a,b].find(x=>!x.isStatic);if(moving&&!boundaries.includes(a)&&!boundaries.includes(b)){points(10);tone(110+Math.random()*80,.025,.018)}let spring=[a,b].find(x=>x.label==='spring');if(spring&&moving&&moving!==spring){Body.applyForce(moving,moving.position,{x:0,y:-.035});points(40);tone(520,.08,.05)}let target=[a,b].find(x=>x.label==='target');if(target&&!activated.has(target.id)){activated.add(target.id);points(250);msg.textContent='TARGET HIT!';tone(760,.18,.08)}})});
let ac=null;function tone(f,d,v){try{ac??=new (AudioContext||webkitAudioContext)();let o=ac.createOscillator(),g=ac.createGain();o.frequency.value=f;o.type='sine';g.gain.setValueAtTime(v,ac.currentTime);g.gain.exponentialRampToValueAtTime(.001,ac.currentTime+d);o.connect(g).connect(ac.destination);o.start();o.stop(ac.currentTime+d)}catch{}}
canvas.addEventListener('pointerdown',e=>{let r=canvas.getBoundingClientRect();add(tool,e.clientX-r.left,e.clientY-r.top)});
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{tool=b.dataset.tool;document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('active',x===b))});document.querySelector('[data-tool=domino]').classList.add('active');
$('#go').onclick=go;$('#reset').onclick=()=>{if(runner)Runner.stop(runner);rebuild()};$('#clear').onclick=()=>{if(mode==='build'){items.forEach(b=>Composite.remove(engine.world,b));items=[];snapshot()}};$('#undo').onclick=()=>{if(mode==='build'&&items.length){Composite.remove(engine.world,items.pop());snapshot()}};
function poly(points,fill,stroke){ctx.beginPath();ctx.moveTo(points[0][0],points[0][1]);for(let i=1;i<points.length;i++)ctx.lineTo(points[i][0],points[i][1]);ctx.closePath();if(fill){ctx.fillStyle=fill;ctx.fill()}if(stroke){ctx.strokeStyle=stroke;ctx.stroke()}}
function shadow(){ctx.shadowColor='rgba(0,0,0,.38)';ctx.shadowBlur=9;ctx.shadowOffsetX=6;ctx.shadowOffsetY=8}
function draw(){let w=canvas.clientWidth,h=canvas.clientHeight;ctx.clearRect(0,0,w,h);
let bg=ctx.createLinearGradient(0,0,0,h);bg.addColorStop(0,'#293342');bg.addColorStop(1,'#171d27');ctx.fillStyle=bg;ctx.fillRect(0,0,w,h);
ctx.save();ctx.globalAlpha=.22;ctx.strokeStyle='#8290a3';ctx.lineWidth=1;for(let y=34;y<h;y+=42){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke()}for(let x=-h;x<w+h;x+=55){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x-h*.28,h);ctx.stroke()}ctx.restore();
items.forEach(b=>{ctx.save();ctx.translate(b.position.x,b.position.y);ctx.rotate(b.angle);ctx.lineWidth=1.5;shadow();
if(b.label==='domino'){ctx.fillStyle='rgba(0,0,0,.25)';ctx.fillRect(1,-22,18,55);ctx.shadowColor='transparent';poly([[-7,-27],[7,-27],[14,-32],[0,-32]],'#ffffff','#c5cfda');poly([[7,-27],[7,27],[14,22],[14,-32]],'#8797aa','#657487');let g=ctx.createLinearGradient(-7,0,7,0);g.addColorStop(0,'#dbe4ee');g.addColorStop(1,'#aebdcb');ctx.fillStyle=g;ctx.fillRect(-7,-27,14,54);ctx.strokeStyle='#f5f8fb';ctx.strokeRect(-7,-27,14,54)}
if(b.label==='ball'){ctx.shadowOffsetX=7;ctx.shadowOffsetY=9;ctx.fillStyle='rgba(0,0,0,.32)';ctx.beginPath();ctx.ellipse(5,8,17,11,0,0,7);ctx.fill();ctx.shadowColor='transparent';let g=ctx.createRadialGradient(-6,-7,2,0,0,18);g.addColorStop(0,'#e7fbff');g.addColorStop(.25,'#79e6ff');g.addColorStop(1,'#1683a7');ctx.fillStyle=g;ctx.beginPath();ctx.arc(0,0,17,0,7);ctx.fill();ctx.strokeStyle='#bdf5ff';ctx.stroke()}
if(b.label==='ramp'){ctx.shadowColor='rgba(0,0,0,.4)';ctx.fillStyle='#536173';ctx.fillRect(-48,0,100,13);ctx.shadowColor='transparent';poly([[-50,-6],[50,-6],[50,5],[-50,5]],'#9eacba','#c8d2dc');poly([[50,-6],[57,-1],[57,10],[50,5]],'#5e6c7c');ctx.fillStyle='#778697';ctx.fillRect(-50,3,100,5)}
if(b.label==='spring'){ctx.fillStyle='#7a5b16';ctx.fillRect(-21,2,46,10);ctx.shadowColor='transparent';ctx.strokeStyle='#ffe28a';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(-18,3);for(let i=-15;i<=15;i+=6)ctx.lineTo(i,(i/6%2)*10-5);ctx.lineTo(18,3);ctx.stroke();ctx.fillStyle='#e6b83e';ctx.fillRect(-23,-8,46,6)}
if(b.label==='target'){ctx.shadowColor='rgba(0,0,0,.4)';ctx.fillStyle='rgba(0,0,0,.3)';ctx.beginPath();ctx.ellipse(5,8,25,20,0,0,7);ctx.fill();ctx.shadowColor='transparent';let hit=activated.has(b.id);ctx.fillStyle=hit?'#163c25':'#48202b';ctx.beginPath();ctx.arc(0,0,24,0,7);ctx.fill();ctx.strokeStyle=hit?'#6cff91':'#ff6b84';ctx.lineWidth=5;ctx.stroke();ctx.beginPath();ctx.arc(0,0,10,0,7);ctx.stroke();ctx.fillStyle=hit?'#9affb2':'#ff9aaa';ctx.beginPath();ctx.arc(-4,-5,4,0,7);ctx.fill()}
ctx.restore()});requestAnimationFrame(draw)}size();draw();